### ISSUE TITLE
WF1 Module 1 (version 2) template undefined node

### ISSUE THREAD

**Issue by alongreyber** [NCATS-Gamma/robokop-rewrite#162] opened 2021-01-25 16:37 UTC
Choosing the WF1 Module 1 (version 2) template leads to an undefined node label:

https://user-images.githubusercontent.com/1634866/105735378-9dae8b80-5f01-11eb-8724-03b480f2418a.mov

**Comment by maximusunc** [comment] 2021-01-25 16:50
This looks to be because the curie in that template is a string, not an array. We should update that template, as well as add a function to convert all string curies to arrays for consistency.

**Comment by maximusunc** [comment] 2021-01-28 15:06
This is a duplicate of #128

**Closed by maximusunc** 2021-01-28 15:06 UTC
Labels: bug
